"""Write a Railway-safe environment template without copying local secrets."""

from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ENV_EXAMPLE = ROOT / ".env.example"
LOCAL_ENV = ROOT / ".env"
OUTPUT = ROOT / "railway.env.template"

SAFE_VALUE_KEYS = {
    "OPENAI_MODEL",
    "GOOGLE_SHEET_TAB_NAME",
    "REDDIT_USER_AGENT",
    "REDDIT_SUBREDDIT",
    "TIKTOK_COOKIES_PATH",
    "POST_TIME_1",
    "POST_TIME_2",
    "POST_TIME_3",
    "ENABLE_REDDIT",
    "ENABLE_TIKTOK",
    "ENABLE_INSTAGRAM",
    "ENABLE_YOUTUBE",
    "MAX_PRODUCTS_PER_POST",
    "MIN_PRODUCTS_PER_POST",
    "VIDEO_SECONDS_PER_IMAGE",
    "MIN_PINTEREST_STOCK",
    "PINTEREST_KEYWORDS",
    "SQLITE_PATH",
    "MUSIC_FOLDER",
    "TEMP_FOLDER",
    "ENABLE_DEBUG_UI",
}

LOCAL_ONLY_KEYS = {
    "NOTION_TOKEN",
    "NOTION_PAGE_ID",
}

REQUIRED_PLACEHOLDERS = {
    "OPENAI_API_KEY": "<set in Railway>",
    "GOOGLE_SERVICE_ACCOUNT_JSON": "<paste full service account JSON or Railway secret>",
    "GOOGLE_SHEET_ID": "<set in Railway if using Sheets>",
    "TELEGRAM_BOT_TOKEN": "<set in Railway>",
    "TELEGRAM_CHAT_ID": "<set in Railway>",
}

OPTIONAL_PLACEHOLDERS = {
    "DRIVE_FOLDER_QUEUE_ID": "<optional: Google Drive queue folder ID>",
    "DRIVE_FOLDER_POSTED_ID": "<optional: Google Drive posted folder ID>",
    "DRIVE_FOLDER_REJECTED_ID": "<optional: Google Drive rejected folder ID>",
    "DRIVE_FOLDER_RAW_PINTEREST_ID": "<optional: Google Drive raw Pinterest folder ID>",
    "REDDIT_CLIENT_ID": "<optional until Reddit approved>",
    "REDDIT_CLIENT_SECRET": "<optional until Reddit approved>",
    "REDDIT_USERNAME": "<optional until Reddit approved>",
    "REDDIT_PASSWORD": "<optional until Reddit approved>",
    "INSTAGRAM_ACCESS_TOKEN": "<optional until Instagram enabled>",
    "INSTAGRAM_USER_ID": "<optional until Instagram enabled>",
    "YOUTUBE_CLIENT_SECRETS_JSON": "<optional until YouTube enabled>",
    "TIKTOK_ACCESS_TOKEN": "<optional until TikTok API enabled>",
    "PIXABAY_API_KEY": "<optional: only needed for external music fallback>",
    "DEBUG_UI_TOKEN": "<optional: protect debug UI with ?token=...>",
}

ORDER = [
    "OPENAI_API_KEY",
    "OPENAI_MODEL",
    "GOOGLE_SERVICE_ACCOUNT_JSON",
    "GOOGLE_SHEET_ID",
    "GOOGLE_SHEET_TAB_NAME",
    "DRIVE_FOLDER_QUEUE_ID",
    "DRIVE_FOLDER_POSTED_ID",
    "DRIVE_FOLDER_REJECTED_ID",
    "DRIVE_FOLDER_RAW_PINTEREST_ID",
    "TELEGRAM_BOT_TOKEN",
    "TELEGRAM_CHAT_ID",
    "REDDIT_CLIENT_ID",
    "REDDIT_CLIENT_SECRET",
    "REDDIT_USERNAME",
    "REDDIT_PASSWORD",
    "REDDIT_USER_AGENT",
    "REDDIT_SUBREDDIT",
    "INSTAGRAM_ACCESS_TOKEN",
    "INSTAGRAM_USER_ID",
    "YOUTUBE_CLIENT_SECRETS_JSON",
    "TIKTOK_COOKIES_PATH",
    "TIKTOK_ACCESS_TOKEN",
    "PIXABAY_API_KEY",
    "POST_TIME_1",
    "POST_TIME_2",
    "POST_TIME_3",
    "ENABLE_REDDIT",
    "ENABLE_TIKTOK",
    "ENABLE_INSTAGRAM",
    "ENABLE_YOUTUBE",
    "MAX_PRODUCTS_PER_POST",
    "MIN_PRODUCTS_PER_POST",
    "VIDEO_SECONDS_PER_IMAGE",
    "MIN_PINTEREST_STOCK",
    "PINTEREST_KEYWORDS",
    "SQLITE_PATH",
    "MUSIC_FOLDER",
    "TEMP_FOLDER",
    "ENABLE_DEBUG_UI",
    "DEBUG_UI_TOKEN",
]


def parse_env_file(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values

    for raw_line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def template_value(key: str, example_values: dict[str, str], local_values: dict[str, str]) -> str:
    if key == "ENABLE_DEBUG_UI":
        return example_values.get(key) or local_values.get(key) or "true"
    if key in REQUIRED_PLACEHOLDERS:
        return REQUIRED_PLACEHOLDERS[key]
    if key in OPTIONAL_PLACEHOLDERS:
        return OPTIONAL_PLACEHOLDERS[key]
    if key in SAFE_VALUE_KEYS:
        return example_values.get(key) or local_values.get(key) or ""
    return "<set in Railway>"


def main() -> None:
    example_values = parse_env_file(ENV_EXAMPLE)
    local_values = parse_env_file(LOCAL_ENV)

    discovered_keys = set(example_values) | set(local_values) | set(ORDER)
    keys = [key for key in ORDER if key in discovered_keys and key not in LOCAL_ONLY_KEYS]
    keys.extend(sorted(discovered_keys - set(keys) - LOCAL_ONLY_KEYS))

    lines = [
        "# Railway environment template for Fashion Affiliate Bot",
        "# Generated by scripts/export_railway_env_template.py",
        "# Safe to commit: real local secrets are replaced with placeholders.",
        "",
    ]
    for key in keys:
        lines.append(f"{key}={template_value(key, example_values, local_values)}")

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT.name} with {len(keys)} variables.")


if __name__ == "__main__":
    main()
